;; Test suite for pipenv.el

(load (expand-file-name "pipenv.el" default-directory))

(ert-deftest pipenv-with-no-active-project ()
  (should (equal (pipenv-where) nil))
  (should (equal (pipenv-venv) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal (pipenv-py) nil))
  (should (equal nil python-shell-virtualenv-path))
  (should (equal nil python-shell-virtualenv-root))
  (should (equal "python" python-shell-interpreter)))

;; (pipenv--build-command)
;; (pipenv--clean-response)
;; (pipenv--command)
;;
;; (pipenv-update)
;; (pipenv-man)
;; (pipenv-version)
;; (pipenv-help)
;; (pipenv-check)
;; (pipenv-graph)
;; (pipenv-install)
;; (pipenv-lock)
;; (pipenv-uninstall)
;; (pipenv-update)
;; (pipenv-project?)
;; (pipenv-set)
;; (pipenv-unset)
